Implements Ledger method for v3.
bitsoex/bitso-java pull request #4
Opened 2016-09-15 15:54 UTC by gera-rcg

Implements Ledger method for v3 and adds a .json test file and a test case.

2016-09-15 16:00 UTC, vogelito commented on pom.xml
> +	</profiles>
Todo este file tiene whitespace changes a un formato que no usamos.

2016-09-15 16:02 UTC, vogelito commented on src/main/java/com/bitso/Bitso.java
> +     */
Me entra duda. Pudiste bajar el Bitso Formatter xml? Parece que estos javadoc comments no siguen el formato.

Puedes tratar de hacer `command+shift+f` para formatear con el formatter.

2016-09-15 16:03 UTC, vogelito commented on src/main/java/com/bitso/Bitso.java
> +    public BitsoLedgerEntry getLedger(String endpoint) {
Sería mejor crear un enum y pasar un enum en vez de pasar un String. Much cleaner use of java.

2016-09-15 16:04 UTC, vogelito commented on src/main/java/com/bitso/Bitso.java
> +                    break;
este switch statement pareciera estar mal. Todos los casos terminan con el mismo `urlSuffix`

2016-09-15 16:08 UTC, vogelito commented on src/main/java/com/bitso/Bitso.java
> +                             // just looked at
Interesante. Esto pareciera ser un problema del formatter que no le gusta la cantidad de caracteres por linea. Le acabo de dar un update al java formatter en el wiki. Lo puedes bajar y ver si esto se regresa a la linea original?

2016-09-15 16:08 UTC, vogelito commented on src/main/java/com/bitso/Bitso.java
> +            // in the 4th position
Mismo comentario que lo del pasado

2016-09-15 16:09 UTC, vogelito commented on src/main/java/com/bitso/BitsoLedgerEntry.java
> +                String createdAt = (String) obj.getJSONObject(i).get("created_at");
Nope. Esto no está bien. Mira tu linea 28 y compárala a esta....

2016-09-15 16:11 UTC, vogelito commented on src/main/java/com/bitso/exchange/Entry.java
> +        StringBuilder sb = new StringBuilder();
Puedes usar:
`return Helpers.fieldPrinter(this);`

2016-09-15 16:11 UTC, vogelito commented on src/test/java/com/bitso/BitsoLedgerEntryTest.java
> +    public final static String BITSO_LEDGER_ENTRY_FULL_NEW_ACCOUNT = "/Users/[usr]/[path-to-file]/bitso-java/src/test/java/com/bitso/bitsoLedgerEntryTest.json";
Unit tests shouldn't require the user to change the file....

2016-09-15 16:13 UTC, vogelito commented on src/test/java/com/bitso/bitsoLedgerEntryTest.json
> +{"success":true,"payload":[]}
This file shouldn't live in the java code file path. Would be best to add a top-level folder with these test cases.

2016-09-15 16:14 UTC, vogelito commented on src/main/java/com/bitso/BitsoLedgerEntry.java
> +import com.bitso.exchange.Entry;
Esto es confuso. Este es un `BitsoLedgerEntry` que tiene una lista de `Entry` objects? No me hace mucho sentido la verdad....

2016-09-15 16:14 UTC, vogelito requested changes

2016-09-15 16:14 UTC, vogelito commented on pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Esto tiene whitespace changes. No usamos tabs en Bitso sino 4 spaces. Por favor revisa el wiki con los estándares de coding y formato. La razón por la cual tenemos un standard de programación es específicamente para no tener estos cambios que son puramente de whitespace.

2016-09-15 19:24 UTC, gera-rcg commented on pom.xml
> +	<modelVersion>4.0.0</modelVersion>
+A reserva de que haya algún estilo en la configuración que aún no haya quedado correcto, parece ya cumplir con el formato después de que me ayudaste a checar los settings de eclipse para archivos de tipo xml, te agradezco.

2016-09-15 19:24 UTC, gera-rcg commented on pom.xml
> +	</profiles>
+Abordado en comentario anterior.

2016-09-15 19:25 UTC, gera-rcg commented on src/main/java/com/bitso/Bitso.java
> +     */
+Intente varias opciones como pasar únicamente el {@link..} a otro renglón, pasar el enunciado a otro renglón después del @param, inclusive revise las opciones del más actual bitso-java-code-format.xml como:
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_parameter" value="do not insert"/>
Pero aparentemente está bien seteado y aún sigue haciendo el resultado obtenido tras presionar Command + Shift + f

2016-09-15 19:25 UTC, gera-rcg commented on src/main/java/com/bitso/Bitso.java
> +    public BitsoLedgerEntry getLedger(String endpoint) {
+Código refactorizado con el enum.

2016-09-15 19:25 UTC, gera-rcg commented on src/main/java/com/bitso/Bitso.java
> +                    break;
+Abordado en comentario anterior.

2016-09-15 19:26 UTC, gera-rcg commented on src/main/java/com/bitso/Bitso.java
> +                             // just looked at
+Ya aplicando el <setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_parameter" value="do not insert"/> con el hotkey Command + Shift + f sigue sucediendo.

2016-09-15 19:26 UTC, gera-rcg commented on src/main/java/com/bitso/Bitso.java
> +            // in the 4th position
+Abordado en comentario anterior.

2016-09-15 19:26 UTC, gera-rcg commented on src/main/java/com/bitso/BitsoLedgerEntry.java
> +import com.bitso.exchange.Entry;
+El nombre de la clase ahora es BitsoLedger la cual procesa el .json y segun los movimientos del usario, ésta contiene una lista de entries o Entry objects.

2016-09-15 20:53 UTC, vogelito commented on src/main/java/com/bitso/Bitso.java
> +                             // just looked at
Aun con el nuevo formatter que está en el wiki? Qué extraño....

2016-09-15 20:54 UTC, vogelito commented on pom.xml
> +	<modelVersion>4.0.0</modelVersion>
Uff, puse los settings mal, una enorme disculpa. Para los archivos xml estamos usando 2 espacios en vez de 4. Sorry!

2016-09-17 13:25 UTC, gera-rcg commented on src/main/java/com/bitso/exchange/Entry.java
> +        StringBuilder sb = new StringBuilder();
+Modificaciones pertinentes llevadas a cabo para usar el método sugerido.

2016-09-17 13:26 UTC, gera-rcg commented on src/test/java/com/bitso/BitsoLedgerEntryTest.java
> +    public final static String BITSO_LEDGER_ENTRY_FULL_NEW_ACCOUNT = "/Users/[usr]/[path-to-file]/bitso-java/src/test/java/com/bitso/bitsoLedgerEntryTest.json";
+Modified the constant to a relative path.

2016-09-17 13:27 UTC, gera-rcg commented on src/test/java/com/bitso/bitsoLedgerEntryTest.json
> +{"success":true,"payload":[]}
+Moved the file with the json objects to a top-level folder. Not sure if also the test cases files have to be moved to the suggested folder, please confirm.

2016-09-17 13:28 UTC, gera-rcg commented on src/main/java/com/bitso/Bitso.java
> +                             // just looked at
+Faltó reescribir la línea correctamente y luego aplicar de nuevo Command + Shift + f, ya ha quedado en una sola línea como se esperaba.

2016-09-17 13:29 UTC, gera-rcg commented on pom.xml
> +	<modelVersion>4.0.0</modelVersion>
+Settings para .xml puestos en dos espacios ahora.

2016-09-17 13:30 UTC, gera-rcg commented on src/main/java/com/bitso/BitsoLedgerEntry.java
> +                String createdAt = (String) obj.getJSONObject(i).get("created_at");
Perdón, no entendí lo que se sugiere en este comment.

2017-01-12 23:57 UTC, closed without merging